# Generated by Django 2.2.1 on 2019-05-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='horario',
        ),
    ]
